# Generated by Django 5.2.3 on 2025-06-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_book_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(db_index=True, max_length=14, verbose_name="ISBN"),
        ),
    ]
